cinema/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from cinema import views
from django.conf.urls.static import static
from core import settings
import cinema.views

router = DefaultRouter()
router.register('filmsviewset', views.FilmsViewSet, basename='filmsviewset')


urlpatterns = [
    path('home/', cinema.views.FilmsView.as_view(), name="home"),
    path('genres/<int:genre_id>/', cinema.views.GenreView.as_view()),
    path('films/', cinema.views.FilmsViewAPIView.as_view()),
    path('', cinema.views.RegisterUser.as_view(), name="registration"),
    path('login/', cinema.views.LoginUser.as_view(), name="login"),
    path('logout/', cinema.views.user_logout, name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += router.urls

core/urls.py
from urllib import request
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core import settings
from core.settings import MEDIA_URL, MEDIA_ROOT
import cinema.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(cinema.urls)),
]

if settings.DEBUG:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

cinema/models.py
from django.db import models


class Movie(models.Model):
    title = models.CharField('Название', max_length=20, blank=False, unique=True)
    premiere = models.DateField('Дата премьеры')
    description = models.TextField('Описание фильма', max_length=500, blank=True)
    poster = models.ImageField('Постер', upload_to='posters', blank=True)
    actors = models.ManyToManyField('Actor', verbose_name='Актер', blank=True)
    genres = models.ManyToManyField('Genre', verbose_name='Жанр', blank=True)

    class Meta:
        verbose_name = 'фильм'
        verbose_name_plural = 'фильмы'

    def __str__(self):
        return self.title


class Genre(models.Model):
    CHOICES = (
        ('fantasy', 'Фэнтези'),
        ('adventures', 'Приключения'),
        ('action', 'Боевик'),
        ('drama', 'Драма'),
        ('thriller', 'Триллер'),
        ('comedy', 'Комедия'),
    )
    genre_title = models.CharField('Жанр', choices=CHOICES, max_length=20,
                                   blank=True)

    class Meta:
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'

    def get_absolute_url(self):
        return f"/genres/{self.pk}/"

    def __str__(self):
        return self.genre_title


class Actor(models.Model):
    first_name = models.CharField('Имя', max_length=20, blank=False)
    last_name = models.CharField('Фамилия', max_length=20, blank=False)
    nickname = models.CharField('Прозвище', max_length=20, blank=True)
    salary = models.DecimalField('Зарплата', max_digits=5, decimal_places=2,
                                 blank=True)
    profile_image = models.ImageField('Фото', upload_to='profile_images',
                                      blank=True)
    has_oscar = models.BooleanField('Лауреат Оскара', default=False,
                                    blank=False)

    class Meta:
        verbose_name = 'актер'
        verbose_name_plural = 'актеры'

    def __str__(self):
        return f"{self.last_name} {self.first_name}"

cinema/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Пароль повторно', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

cinema/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, CreateView
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from cinema import models, serializers, filters
from .utils import *
from cinema import models
from cinema.forms import RegisterUserForm, LoginUserForm


def normalize_number(number):
    if number // 10 == 0:
        number = '0' + str(number)
    return number


def get_current_date_time():
    current_date = datetime.now()
    current_day = current_date.day
    current_month = current_date.month
    current_year = current_date.year

    current_hour = current_date.hour
    current_minutes = current_date.minute

    current_day = normalize_number(current_day)
    current_month = normalize_number(current_month)
    current_hour = normalize_number(current_hour)
    current_minutes = normalize_number(current_minutes)
    dict_of_datetime = {
        "current_year": current_year,
        "current_day": current_day,
        "current_month": current_month,
        "current_hour": current_hour,
        "current_minutes": current_minutes
    }
    return dict_of_datetime


def login(request):
    return HttpResponseRedirect(reverse('home'))


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'core/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def user_logout(request):
    logout(request)
    return redirect('login')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))


class FilmsView(TemplateView):
    model = models.Movie
    context_object_name = "film"
    template_name = 'core/index.html'

    def get_filters(self):
        return filters.Movie(self.request.GET)

    def get_queryset(self):
        return self.get_filters().qs

    def get_context_data(self, **kwargs):
        context = {
            'films': self.get_queryset(),
            'genres': models.Genre.objects.all(),
            'title': 'Киноафиша',
            'datetime': get_current_date_time,
        }
        context['filters'] = self.get_filters()
        return context


class FilmsViewAPIView(APIView):
    def get(self, request):
        films_qs = models.Movie.objects.all()
        serializer = serializers.Movie(films_qs, many=True)
        titles = [film.title for film in films_qs]
        return Response(data=serializer.data)

    def post(self, request):
        serializer = serializers.Movie(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({'message': 'Фильм добавлен'})


class FilmsViewSet(ModelViewSet):
    queryset = models.Movie.objects.all()
    filterset_class = filters.Movie
    serializer_class = serializers.Movie


class GenreView(TemplateView):
    template_name = 'core/genre.html'

    def get_context_data(self, **kwargs):
        genre_id = kwargs['genre_id']
        films = models.Movie.objects.filter(genres=genre_id)
        genres = models.Genre.objects.all()
        count = models.Movie.objects.filter(genres=genre_id).count()
        datetime = get_current_date_time
        context = {
            'films': films,
            'genres': genres,
            'count': count,
            'datetime': datetime
        }
        return context

core/templates/core/genre.html
{% extends 'base.html' %}
{% block style %}
    <link href="/../static/css/style.css" rel="stylesheet">
{% endblock %}
{% block title %}
<title>{{count}}</title>
{% endblock %}
{% block sidebar %}
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item" id="first-list-group">Поиск по жанрам</li>
            {% for genre in genres %}
                <li class="list-group-item"><a href="/genres/{{ genre.pk }}">{{ genre.get_genre_title_display }}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block content %}
    <div class="col-md-9">
        {% if count == 0 %}
            <p>Фильмов данной категории пока нет!</p>
        {% else %}
        {% for item in films %}
        <div class="card mb-3">
            <img src="/media/{{ item.poster }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ item.title }}</h5>
                <p class="card-text">{{ item.description }}</p>
                <p class="card-text">
                    <small class="text-body-secondary">
                        Актер(-ы):
                        {% for actor in item.actors.all %}
                            {{ actor.first_name }} {{ actor.last_name }}
                            {% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </small>
                </p>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block style %}
    <link href="../static/css/style.css" rel="stylesheet">
{% endblock %}
{% block sidebar %}
    <div class="col-md-3">
        <div class="card-body">
            <form method="get">
                {{ filters.form.as_p }}
                <div class="btn-group" role="group" aria-label="Поиск">
                    <button type="submit" class="btn btn-primary">Поиск</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="col-md-9">
{% for item in films %}
<div class="card mb-3">
    <img src="/media/{{ item.poster }}" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">{{ item.title }}</h5>
        <p class="card-text">{{ item.description }}</p>
        <p class="card-text">
            <small class="text-body-secondary">
                Актер(-ы):
                {% for actor in item.actors.all %}
                    {{ actor.first_name }} {{ actor.last_name }}
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </small>
        </p>
    </div>
</div>
{% endfor %}
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block style %}
<link href="../static/css/style.css" rel="stylesheet">
{% endblock %}
{% block time %}{% endblock %}
{% block content %}
<!--<div class="container d-flex justify-content-center mt-3" style="background-color: #DCDCDC; width: 50%; height: 500px; border-radius: 20px;">-->
<!--    <form method="post" style="margin-top: 20%;">-->
<!--    {% csrf_token %}-->
<!--        <div class="error_in_form">-->
<!--            {{ form.non_field_errors }}-->
<!--        </div>-->
<!--        {% for item in forms %}-->
<!--        <p><label class="form-label" for="{{ item.id_for_label }}">{{ item.label }}: </label>{{ item }}</p>-->
<!--        <div class="error_in_form">{{ item.errors }}</div>-->
<!--        {% endfor %}-->
<!--&lt;!&ndash;    {{ form.as_p }}&ndash;&gt;-->
<!--    <button type="submit">Войти</button>-->
<!--</form>-->
<!--</div>-->
<form method="post">
    {% csrf_token %}

    {% for f in form %}
    <p><label class="form-label"
              for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Регистрация</button>
</form>
{% endblock %}
{% block footer %}
{% endblock %}

core/templates/core/register.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block style %}
    <link href="../static/css/style.css" rel="stylesheet">
{% endblock %}
{% block time %}{% endblock %}
{% block content %}
<div class="container d-flex justify-content-center mt-3" style="background-color: #DCDCDC; width: 50%; height: 500px; border-radius: 20px;">
    <form method="post" style="margin-top: 20%;">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Регистрация</button>
</form>
</div>
{% endblock %}
{% block footer %}
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block style %}
    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    {% block title %}
    <title>{{ title }}</title>
    {% endblock %}
</head>
<body>
{% include 'inc/_navbar.html' %}
{% block time %}
<div class="container mt-3" style="text-align: end;">
    <p>Местное время:
        {{datetime.current_hour}}:{{datetime.current_minutes}}</p>
    <p>Текущая дата: {{datetime.current_day}}.{{datetime.current_month}}.{{ datetime.current_year }}</p>
</div>
{% endblock %}
<div class="container mt-3">
    <div class="row">
        {% block sidebar %}
            {% block buttons %}
            {% endblock buttons %}
        {% endblock %}
        {% block content %}

        {% endblock %}
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
{% block footer %}
{% include 'inc/_footer.html' %}
{% endblock %}
</html>

templates/inc/_footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Афиша</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Актеры</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Рецензии</a></li>
    </ul>
    <p class="text-center text-body-secondary">© 2024 Кинопленка, Inc</p>
</footer>

templates/inc/_navbar.html
<!--<nav class="navbar navbar-expand-lg bg-body-tertiary">-->
<!--    <div class="container-fluid">-->
<!--        <a class="navbar-brand" href="/">Сайт «Кинопленка»</a>-->
<!--        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"-->
<!--                data-bs-target="#navbarNav" aria-controls="navbarNav"-->
<!--                aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarNav">-->
<!--            <ul class="navbar-nav mr-auto">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link active" aria-current="page"-->
<!--                       href="/">{{ title }}</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Актеры</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Рецензии</a>-->
<!--                </li>-->
<!--                {% if not request.user.is_authenticated %}-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>-->
<!--                </li>-->
<!--                {% endif %}-->
<!--            </ul>-->
<!--            {% if request.user.is_authenticated %}-->
<!--            <ul class="navbar-nav">-->
<!--                <li class="nav-item ml-auto">-->
<!--                    <p class="nav-link">{{ user.username }}</p>-->
<!--                </li>-->
<!--            </ul>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--</nav>-->


<!--<nav class="navbar navbar-expand-lg bg-body-tertiary">-->
<!--    <div class="container-fluid">-->
<!--        <a class="navbar-brand" href="/">Сайт «Кинопленка»</a>-->
<!--        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"-->
<!--                data-bs-target="#navbarNav" aria-controls="navbarNav"-->
<!--                aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarNav">-->
<!--            <ul class="navbar-nav mr-auto">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link active" aria-current="page"-->
<!--                       href="/">{{ title }}</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Актеры</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Рецензии</a>-->
<!--                </li>-->
<!--                {% if not request.user.is_authenticated %}-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>-->
<!--                </li>-->
<!--                {% endif %}-->
<!--                {% if request.user.is_authenticated %}-->
<!--                <li class="nav-item">-->
<!--                    <p class="nav-link">{{ user.username }}</p>-->
<!--                </li>-->
<!--                {% endif %}-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
<!--</nav>-->


<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Сайт «Кинопленка»</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">{{ title }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Актеры</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Рецензии</a>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link">{{ user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'registration' %}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>